accounts:
  - name: alice
    coins: ["1000token", "1000andr"]
  - name: bob
    coins: ["1000token", "1000andr"]
validator:
  name: alice
  staked: "1000andr"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: [ "1000andr" ]
  coins_max: [ "1000andr" ]
build:
  binary: "andromad"
  main: "cmd/andromad"
validator:
  name: alice
  staked: "1000andr"
#host:
#  rpc: ":26659"
#  p2p: ":26658"
#  prof: ":6060"
#  grpc: ":9090"
#  api: ":1318"
genesis:
  chain_id: "androma-1"
  app_state:
    staking:
      params:
        bond_denom: "andr"
    mint:
      params:
        mint_denom: "andr"
    crisis:
      constant_fee:
        denom: "andr"
    gov:
      deposit_params:
        min_deposit:
          - amount: "100"
            denom: "andr"
